[project]
name = "roomie-backend"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "thaynabecker", email = "thaynabecker.ifcaraquari@gmail.com"},
    {name = "juliacdss", email = "juliacostaifc@gmail.com"},
]
dependencies = [
    "django>=5.2.4",
    "djangorestframework>=3.16.0",
    "djangorestframework-simplejwt>=5.5.1",
]
requires-python = "==3.10.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
