# Generated by Django 5.2.4 on 2025-07-08 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Republica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_republica', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('codigo_acesso', models.CharField(max_length=20)),
                ('data_criacao', models.DateField()),
            ],
            options={
                'verbose_name': 'República',
                'verbose_name_plural': 'Repúblicas',
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('republica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='roomie.republica')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('republica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departamentos', to='roomie.republica')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('data_entrada', models.DateField()),
                ('republica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='roomie.republica')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_execucao', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], max_length=15)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='roomie.departamento')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='roomie.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado')], max_length=10)),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='roomie.despesa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='roomie.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='usuarios',
            field=models.ManyToManyField(related_name='departamentos', to='roomie.usuario'),
        ),
        migrations.CreateModel(
            name='ChatMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField()),
                ('republica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensagens', to='roomie.republica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensagens', to='roomie.usuario')),
            ],
            options={
                'verbose_name': 'Mensagem de Chat',
                'verbose_name_plural': 'Mensagens de Chat',
            },
        ),
        migrations.CreateModel(
            name='Advertencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('grave', 'Grave')], max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertencias', to='roomie.usuario')),
            ],
            options={
                'verbose_name': 'Advertência',
                'verbose_name_plural': 'Advertências',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='roomie.usuario')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
    ]
