# Generated by Django 5.2.4 on 2025-08-24 14:50

import roomie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', roomie.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
